from typing import Protocol, runtime_checkable


@runtime_checkable
class Updater(Protocol):
    def read_version(self, contents: str) -> str: ...
    def write_version(self, contents: str, version: str) -> str: ...
    def is_private(self, contents: str) -> bool: ...
